# Generated by Django 5.0.4 on 2024-04-18 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='Choose your product', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
